### ISSUE TITLE
Export to pdf not working in 0.5.1

### ISSUE THREAD

**Issue by MaikH88** [ZellMechanik-Dresden/ShapeOut#33]
Error-message:
...
line 349, in OnMenuExportPDF
AttributeError: 'PlotPanel' object has no attribute 'container'
